import type { Metadata } from "next";

// ✅ Metadata must live here (server component)
export const metadata: Metadata = {
  title: "Fire ‘n Ice",
  description: "Generated by create next app",
};

// Render your actual client layout
import ClientLayout from "./ClientLayout";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <ClientLayout>{children}</ClientLayout>;
}
